theme: minima
title: C++ for Robotics
description: Modern, safe, and clean control software for the physical world

markdown: kramdown
highlighter: rouge

kramdown
  syntax_highlighter: rouge

include:
  - assets